# Модуль NumPy

In [2]:
print("Hello, Jupyter")

Hello, Jupyter


In [3]:
# установка NumPy
!pip install numpy

In [5]:
# импортирование модуля (библиотеки, фреймворки)
import numpy as np

- Создание массивов 

In [7]:
# создание вектор-строка (1-мерный массив) из строки
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [8]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [9]:
# создание массива (вектор-строки) из нулей
z = np.zeros(10)
z 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# создание вектор-столбца из нулей
# (кол-во строк, кол-во столбцов)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# создание матрицы из нулей 
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# метод, который создает вектор строку со значениями из линейнрй последовательноси 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10, 100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [15]:
# вектор-строка со значениями из равномерного распределения
# например, от 0 до 1
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
# случайные значения из равномерного распределния от 0 до 1
np.random.random(5)

array([0.75166719, 0.27344532, 0.32111264, 0.80897926, 0.68721559])

In [19]:
np.random.random((3,3))

array([[0.54188855, 0.23010921, 0.90907072],
       [0.83787825, 0.86857221, 0.65003395],
       [0.76869287, 0.11915415, 0.32904256]])

In [20]:
# случайные целые значения
# случайное число от 0 до 10
np.random.randint(10)

3

In [21]:
# вектор-строка со знчениями от 0 до 10 размером (длиной) 5
np.random.randint(10, size=5)

array([5, 2, 1, 1, 9])

In [22]:
# матрица формой 2 на 3 со случайными значениями от 10 до 20
np.random.randint(10, 20, size=(2,3))

array([[17, 16, 12],
       [13, 19, 19]])

- атрибуты 

In [23]:
a = np.random.randint(10, size=(3,5))
a

array([[0, 8, 2, 9, 3],
       [1, 7, 5, 0, 7],
       [1, 9, 6, 9, 3]])

In [24]:
# размерность массива - кол-во измерений/осей
a.ndim

2

In [25]:
# форма массива
a.shape

(3, 5)

In [26]:
# кол-во всех элементов массива
a.size


15

In [27]:
# тип значений массива
a.dtype

dtype('int64')

In [29]:
# a.astype("float16")

array([[0., 8., 2., 9., 3.],
       [1., 7., 5., 0., 7.],
       [1., 9., 6., 9., 3.]], dtype=float16)