# Модуль NumPy

In [2]:
print("Hello, Jupyter")

Hello, Jupyter


In [3]:
# установка NumPy
!pip install numpy

In [5]:
# импортирование модуля (библиотеки, фреймворки)
import numpy as np

- Создание массивов 

In [7]:
# создание вектор-строка (1-мерный массив) из строки
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [8]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [9]:
# создание массива (вектор-строки) из нулей
z = np.zeros(10)
z 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# создание вектор-столбца из нулей
# (кол-во строк, кол-во столбцов)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# создание матрицы из нулей 
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# метод, который создает вектор строку со значениями из линейнрй последовательноси 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10, 100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [15]:
# вектор-строка со значениями из равномерного распределения
# например, от 0 до 1
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
# случайные значения из равномерного распределния от 0 до 1
np.random.random(5)

array([0.75166719, 0.27344532, 0.32111264, 0.80897926, 0.68721559])

In [19]:
np.random.random((3,3))

array([[0.54188855, 0.23010921, 0.90907072],
       [0.83787825, 0.86857221, 0.65003395],
       [0.76869287, 0.11915415, 0.32904256]])

In [20]:
# случайные целые значения
# случайное число от 0 до 10
np.random.randint(10)

3

In [21]:
# вектор-строка со знчениями от 0 до 10 размером (длиной) 5
np.random.randint(10, size=5)

array([5, 2, 1, 1, 9])

In [22]:
# матрица формой 2 на 3 со случайными значениями от 10 до 20
np.random.randint(10, 20, size=(2,3))

array([[17, 16, 12],
       [13, 19, 19]])

- атрибуты 

In [23]:
a = np.random.randint(10, size=(3,5))
a

array([[0, 8, 2, 9, 3],
       [1, 7, 5, 0, 7],
       [1, 9, 6, 9, 3]])

In [24]:
# размерность массива - кол-во измерений/осей
a.ndim

2

In [25]:
# форма массива
a.shape

(3, 5)

In [26]:
# кол-во всех элементов массива
a.size


15

In [27]:
# тип значений массива
a.dtype

dtype('int64')

#  a.astype("float16")

- Индексация 


In [2]:
import numpy as np

In [3]:
a2 = np.random.randint(10, size=10)
a2

array([1, 5, 8, 3, 4, 8, 7, 3, 1, 1])

In [5]:
# чтение значений 
a2[0]

NameError: name 'a2' is not defined

In [5]:
a2[-4]

7

In [6]:
# изменение значений 
a2[1] = 10
a2

array([ 1, 10,  8,  3,  4,  8,  7,  3,  1,  1])

In [7]:
a3 = np.random.randint(10, size=(3,5))
a3

array([[9, 6, 0, 9, 9],
       [7, 6, 3, 1, 6],
       [1, 3, 6, 0, 2]])

In [8]:
# стандартный питоновский способ
a3[0][2]

0

In [9]:
# способ NumPy
# [индексы строк, индекс столбцов]
a3[0, 2]

0

- Срезы

In [10]:
# срез по строкам 
a3[1:]

array([[7, 6, 3, 1, 6],
       [1, 3, 6, 0, 2]])

In [11]:
# срез по строкам от 1 индекса до конца
# срез по столбцам от 1 начала до 3 инд. не включительно
a3[1:, :3]

array([[7, 6, 3],
       [1, 3, 6]])

In [12]:
a3[:, 2:]

array([[0, 9, 9],
       [3, 1, 6],
       [6, 0, 2]])

- Представление (views) и копии (copies)


In [13]:
# список
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [14]:
# вектор строка 
my_arr = np.array(my_list)
my_arr

array([1, 2, 3, 4, 5])

In [15]:
# српез списка
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [16]:
# срез вектор-строки
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [17]:
sub_list[0] = 100
my_list

[1, 2, 3, 4, 5]

In [18]:
# массив, созданный срезом другого масиива яв-ся в.т.ч представлением 
# поэтому изменения в массиве-представления отражаются на исходный массив
sub_arr[0] = 100
my_arr

array([  1,   2, 100,   4,   5])

In [19]:
# копия массива
copy_arr = my_arr[:2].copy()
copy_arr

array([1, 2])

In [20]:
copy_arr[0] = 5
my_arr

array([  1,   2, 100,   4,   5])

- Изменение формы 

In [21]:
# 1- мерный массив (вектор-строка)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr.shape

(9,)

In [23]:
# изменение формы - создание вектор-столбца
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
# изменение формы - создание матрицы
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- универсальные функции 

In [25]:
a = np.array([1,2,3,4,5])
b = np.array([20,30,40,50,60])
print(a)
print(b)


[1 2 3 4 5]
[20 30 40 50 60]


In [26]:
# поэлементное деление 
a / b

array([0.05      , 0.06666667, 0.075     , 0.08      , 0.08333333])

In [27]:
# деление на скалярное значение 
a / 100

array([0.01, 0.02, 0.03, 0.04, 0.05])

In [28]:
100 / b

array([5.        , 3.33333333, 2.5       , 2.        , 1.66666667])

In [29]:
a > b

array([False, False, False, False, False])

In [30]:
a < 4

array([ True,  True,  True, False, False])

-  агрегирование 


In [7]:
# агрегирование -  вычисление неких сводных показателей
arr_2 = np.random.random(10)
arr_2

NameError: name 'np' is not defined

In [33]:
# сумма 
np.sum(arr_2)

6.7434844798534055

In [34]:
# минимальное значение 
np.min(arr_2)

0.3583052760870047

In [35]:
# среднее арифметическое 
np.mean(arr_2)


0.6743484479853405

- маскирование 


In [37]:
# извлечение значений которые отвечают некоторому условию
x = np.random.randint(10, size=7)
x

array([5, 2, 3, 8, 9, 8, 3])

In [38]:
x < 5

array([False,  True,  True, False, False, False,  True])

In [39]:
# только те значения, которые отвечают услвоию ( меньше 5)
x[x < 5]

array([2, 3, 3])

In [40]:
# те значения, которые отвечают меньше 5 меняются на 0
x[x < 5] = 0
x

array([5, 0, 0, 8, 9, 8, 0])

- прихотливая индексация 


In [41]:
# "прихотливая" индексация - выбор значений по определенным индексам 
x = np.random.randint(10, size=7)
x

array([5, 9, 5, 3, 3, 4, 4])

In [43]:
# выбор значений по массиву с индексами, который находится в переменной indices
x[[5,0,2]]

array([4, 5, 5])

In [44]:
indices = np.array([5,0,3])
x[indices]

array([4, 5, 3])

In [46]:
x2 = np.random.randint(10, size=(3,5))
x2

array([[2, 7, 5, 3, 8],
       [0, 6, 0, 8, 8],
       [3, 1, 9, 4, 1]])

In [49]:
# сочетание среза и прихотливой индексации
x2[1:, [2,0]]

array([[0, 0],
       [9, 3]])

In [50]:
x2<5

array([[ True, False, False,  True, False],
       [ True, False,  True, False, False],
       [ True,  True, False,  True,  True]])

In [52]:
# сочетание маскирования и прихотливой индексации
x2[x2>5][[5,0,3]]

array([9, 7, 8])